apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k8s-net
  labels:
    app: hello-world-k8s-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-k8s-net
  template:
    metadata:
      labels:
        app: hello-world-k8s-net
    spec:
      containers:
        - name: hello-world-k8s-net
          image: robyconte/hello-world-k8s-net
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATA_PATH
              value: "/app/data"
          volumeMounts:
            - name: data
              mountPath: /app/data
      imagePullSecrets:
        - name: dockerhub
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage
