apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: aks.robertoconterosito.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helloworld-net
                port:
                  number: 80
  tls:
    - hosts:
        - aks.robertoconterosito.it
      secretName: tls-secret
